/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIGCCanvas: typeof import('./src/components/Canvas.vue')['default']
    AssetList: typeof import('./src/components/AssetList.vue')['default']
    Canvas: typeof import('./src/components/Canvas.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HumanFigure: typeof import('./src/components/HumanFigure.vue')['default']
    PropertyPanel: typeof import('./src/components/PropertyPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestDemo: typeof import('./src/components/Toolbar.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
  }
}

// For TSX support
declare global {
  const AIGCCanvas: typeof import('./src/components/Canvas.vue')['default']
  const AssetList: typeof import('./src/components/AssetList.vue')['default']
  const Canvas: typeof import('./src/components/Canvas.vue')['default']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElImage: typeof import('element-plus/es')['ElImage']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElUpload: typeof import('element-plus/es')['ElUpload']
  const HumanFigure: typeof import('./src/components/HumanFigure.vue')['default']
  const PropertyPanel: typeof import('./src/components/PropertyPanel.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TestDemo: typeof import('./src/components/Toolbar.vue')['default']
  const Toolbar: typeof import('./src/components/Toolbar.vue')['default']
}